version: "3.8"

services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HTTP_PORT}:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]