name: release
channels:
  - defaults
  - rdkit
  - pytorch
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - seaborn=0.9.0
  - scikit-learn
  - scipy
  - pytest
  - pytest-cov
  - ipython
  - ipykernel
  - rdkit
  - nox
  - cairo
